### ISSUE TITLE
You could implement decimals in frequency Ver 2

### ISSUE THREAD

**Issue by CarlosNet** [RobTillaart/AD985X#20]
Hello again Rob.
something happens with the last updates in the decimal version, which does not change the frequency when uploading.
it only changes integers not decimals.
Can you check to see if something changed in the code?
if I change values ​​below the decimal places, the frequency does not change

**Comment by RobTillaart** [comment]
@CarlosNet 

Does the problem still exist?

Note that to set floating point values one need to use the setFrequency**F**() function.
Maybe you missed that difference?

Added both to be able to maximize the range of settings.

```cpp
    void     setFrequency(uint32_t freq);         // 0..AD9850_MAX_FREQ
    void     setFrequencyF(float freq);           // works best for lower frequencies.
```
