### ISSUE TITLE
`AD9851::setRefClockHigh()` doesn't work

### ISSUE THREAD

**Issue by wh201906** [RobTillaart/AD985X#33]
To reproduce this bug:
```
ad9851.begin();
ad9851.powerUp();
ad9851.setAutoRefClock(false);
ad9851.setRefClockHigh();
ad9851.setFrequency(1000);
```
The output frequency is not 1kHz.
***
This can be fixed by #32

**Comment by RobTillaart** [comment]
@wh201906 
See comments in PR #32

**Comment by RobTillaart** [comment]
@wh201906
if time permits, could you test the develop branch. 
In my test it seems to work - tested the value of the mask depending on type - as I have no hardware setup nearby.
Will merge later today.

**Comment by wh201906** [comment]
I only have an AD9851 so I can only test that

**Comment by RobTillaart** [comment]
That would be sufficient as for the AD9850 there is nothing changed.
When I create 2 objects and print their mask I get the right mask.
So I'm confident it works, but as always proof with real hardware is proof.

**Comment by wh201906** [comment]
@RobTillaart I‘ve tested the code in the `develop` branch. It's working on AD9851.

I tried `AD9851::setRefClockLow();` and `AD9851::setRefClockHigh();`, both have the right output frequency.
Thanks!
